<template>
    <div class="header">
        <router-link to="/course" class="login">
            <span>天擎智教</span>
            <span class="sizes">后台管理</span>
        </router-link>
        <router-link @click="navChange" :to="list.url" v-for="(list, index) in nav" :class="navs === list.isNav ? 'list yes-list' : 'list'" :key="index">{{list.name}}</router-link>
    </div>
</template>

<script>
  import {menuList} from '@/api/login'
  export default {
    props:['navs'],
    data(){
      return{
        nav:[
          {
            name:'课程中心',
            url:'/course',
            isNav:'course'
          },
          {
            name:'学习管理',
            url:'/learn/index',
            isNav:'learn'
          },
          {
            name:'校管中心',
            url:'/school',
            isNav:'school'
          },
          {
            name:'系统管理',
            url:'/system',
            isNav:'system'
          }
        ],
        menuList:[{
	"menuId": 6,
	"name": "数据中心",
	"parentId": 0,
	"url": null,
	"perms": null,
	"type": 0,
	"icon": null,
	"orderNo": null,
	"open": null,
	"list": [],
	"parentName": null
}, {
	"menuId": 3,
	"name": "课程中心",
	"parentId": 0,
	"url": null,
	"perms": null,
	"type": 0,
	"icon": null,
	"orderNo": 1,
	"open": null,
	"list": [{
		"menuId": 170,
		"name": "课程列表",
		"parentId": 3,
		"url": 'list',
		"perms": null,
		"type": 1,
		"icon": null,
		"orderNo": null,
		"open": null,
		"list": null,
		"parentName": "课程中心"
	}, {
		"menuId": 171,
		"name": "课程评价",
		"parentId": 3,
		"url": null,
		"perms": null,
		"type": 0,
		"icon": null,
		"orderNo": null,
		"open": null,
		"list": [{
			"menuId": 175,
			"name": "课程评价列表",
			"parentId": 171,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "课程评价"
		}],
		"parentName": "课程中心"
	}, {
		"menuId": 172,
		"name": "资源管理",
		"parentId": 3,
		"url": null,
		"perms": null,
		"type": 0,
		"icon": null,
		"orderNo": null,
		"open": null,
		"list": [{
			"menuId": 176,
			"name": "试题管理",
			"parentId": 172,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "资源管理"
		}, {
			"menuId": 177,
			"name": "资源管理",
			"parentId": 172,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "资源管理"
		}, {
			"menuId": 178,
			"name": "活动管理",
			"parentId": 172,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "资源管理"
		}],
		"parentName": "课程中心"
	}, {
		"menuId": 265,
		"name": "讲师",
		"parentId": 3,
		"url": "course/instructor",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "课程中心"
	}, {
		"menuId": 270,
		"name": "笔记",
		"parentId": 3,
		"url": "course/note",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "课程中心"
	}, {
		"menuId": 275,
		"name": "课程章",
		"parentId": 3,
		"url": "course/catalogchapter",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "课程中心"
	}, {
		"menuId": 280,
		"name": "课件小项",
		"parentId": 3,
		"url": "course/catalogitem",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "课程中心"
	}, {
		"menuId": 285,
		"name": "课程节",
		"parentId": 3,
		"url": "course/catalogsection",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "课程中心"
	}, {
		"menuId": 290,
		"name": "投票问卷",
		"parentId": 3,
		"url": "course/vote",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "课程中心"
	}, {
		"menuId": 305,
		"name": "资源",
		"parentId": 3,
		"url": "course/libraryresource",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "课程中心"
	}, {
		"menuId": 315,
		"name": "主观练习题",
		"parentId": 3,
		"url": "course/libraryquiz",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "课程中心"
	}, {
		"menuId": 325,
		"name": "课程测试",
		"parentId": 3,
		"url": "course/exam",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "课程中心"
	}, {
		"menuId": 330,
		"name": "用户选课",
		"parentId": 3,
		"url": "course/courseuser",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "课程中心"
	}, {
		"menuId": 335,
		"name": "课程-分组-用户",
		"parentId": 3,
		"url": "course/courseteamuser",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "课程中心"
	}, {
		"menuId": 340,
		"name": "课程-方案-分组",
		"parentId": 3,
		"url": "course/courseteam",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "课程中心"
	}, {
		"menuId": 345,
		"name": "课程-分组方案",
		"parentId": 3,
		"url": "course/coursescheme",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "课程中心"
	}, {
		"menuId": 360,
		"name": "课程成绩设置",
		"parentId": 3,
		"url": "course/courseassistant",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "课程中心"
	}, {
		"menuId": 368,
		"name": "头脑风暴",
		"parentId": 3,
		"url": "course/storm",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "课程中心"
	}, {
		"menuId": 373,
		"name": "投票问卷",
		"parentId": 3,
		"url": "course/vote",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "课程中心"
	}, {
		"menuId": 378,
		"name": "作业",
		"parentId": 3,
		"url": "course/homework",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "课程中心"
	}, {
		"menuId": 125,
		"name": "课程管理",
		"parentId": 3,
		"url": "course/course",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "课程中心"
	}, {
		"menuId": 383,
		"name": "活动",
		"parentId": 3,
		"url": "course/interaction",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "课程中心"
	}, {
		"menuId": 385,
		"name": "学生提交作业",
		"parentId": 3,
		"url": "course/homeworksubmission",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "课程中心"
	}, {
		"menuId": 220,
		"name": "租户",
		"parentId": 3,
		"url": "course/systenant",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "课程中心"
	}],
	"parentName": null
}, {
	"menuId": 5,
	"name": "学习管理",
	"parentId": 0,
	"url": null,
	"perms": null,
	"type": 0,
	"icon": null,
	"orderNo": 2,
	"open": null,
	"list": [{
		"menuId": 180,
		"name": "学习管理",
		"parentId": 5,
		"url": null,
		"perms": null,
		"type": 1,
		"icon": null,
		"orderNo": null,
		"open": null,
		"list": null,
		"parentName": "学习管理"
	}],
	"parentName": null
}, {
	"menuId": 4,
	"name": "校管中心",
	"parentId": 0,
	"url": null,
	"perms": null,
	"type": 0,
	"icon": null,
	"orderNo": 3,
	"open": null,
	"list": [{
		"menuId": 183,
		"name": "用户管理",
		"parentId": 4,
		"url": null,
		"perms": null,
		"type": 0,
		"icon": null,
		"orderNo": null,
		"open": null,
		"list": [{
			"menuId": 184,
			"name": "学生管理",
			"parentId": 183,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "用户管理"
		}, {
			"menuId": 185,
			"name": "教师管理",
			"parentId": 183,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "用户管理"
		}, {
			"menuId": 186,
			"name": "管理员",
			"parentId": 183,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "用户管理"
		}],
		"parentName": "校管中心"
	}, {
		"menuId": 187,
		"name": "门户配置",
		"parentId": 4,
		"url": null,
		"perms": null,
		"type": 0,
		"icon": null,
		"orderNo": null,
		"open": null,
		"list": [{
			"menuId": 188,
			"name": "模板配置",
			"parentId": 187,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "门户配置"
		}, {
			"menuId": 189,
			"name": "平台信息",
			"parentId": 187,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "门户配置"
		}, {
			"menuId": 190,
			"name": "轮播图",
			"parentId": 187,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "门户配置"
		}, {
			"menuId": 191,
			"name": "课程推荐",
			"parentId": 187,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "门户配置"
		}, {
			"menuId": 192,
			"name": "名师风采",
			"parentId": 187,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "门户配置"
		}],
		"parentName": "校管中心"
	}, {
		"menuId": 193,
		"name": "课程管理",
		"parentId": 4,
		"url": null,
		"perms": null,
		"type": 0,
		"icon": null,
		"orderNo": null,
		"open": null,
		"list": [{
			"menuId": 194,
			"name": "课程管理",
			"parentId": 193,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "课程管理"
		}, {
			"menuId": 195,
			"name": "证书审核",
			"parentId": 193,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "课程管理"
		}],
		"parentName": "校管中心"
	}, {
		"menuId": 196,
		"name": "组织架构",
		"parentId": 4,
		"url": null,
		"perms": null,
		"type": 0,
		"icon": null,
		"orderNo": null,
		"open": null,
		"list": [{
			"menuId": 197,
			"name": "院系管理",
			"parentId": 196,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "组织架构"
		}, {
			"menuId": 198,
			"name": "专业管理",
			"parentId": 196,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "组织架构"
		}, {
			"menuId": 199,
			"name": "班级管理",
			"parentId": 196,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "组织架构"
		}],
		"parentName": "校管中心"
	}],
	"parentName": null
}, {
	"menuId": 1,
	"name": "系统管理",
	"parentId": 0,
	"url": null,
	"perms": null,
	"type": 0,
	"icon": "system",
	"orderNo": 4,
	"open": null,
	"list": [{
		"menuId": 202,
		"name": "门户配置",
		"parentId": 1,
		"url": null,
		"perms": null,
		"type": 0,
		"icon": null,
		"orderNo": null,
		"open": null,
		"list": [{
			"menuId": 203,
			"name": "模板配置",
			"parentId": 202,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "门户配置"
		}, {
			"menuId": 204,
			"name": "平台信息",
			"parentId": 202,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "门户配置"
		}, {
			"menuId": 205,
			"name": "轮播图",
			"parentId": 202,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "门户配置"
		}, {
			"menuId": 206,
			"name": "课程推荐",
			"parentId": 202,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "门户配置"
		}, {
			"menuId": 207,
			"name": "名师风采",
			"parentId": 202,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "门户配置"
		}],
		"parentName": "系统管理"
	}, {
		"menuId": 208,
		"name": "租户管理",
		"parentId": 1,
		"url": null,
		"perms": null,
		"type": 0,
		"icon": null,
		"orderNo": null,
		"open": null,
		"list": [{
			"menuId": 209,
			"name": "租户管理",
			"parentId": 208,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "租户管理"
		}, {
			"menuId": 210,
			"name": "租户账号管理",
			"parentId": 208,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "租户管理"
		}],
		"parentName": "系统管理"
	}, {
		"menuId": 211,
		"name": "系统管理",
		"parentId": 1,
		"url": null,
		"perms": null,
		"type": 0,
		"icon": null,
		"orderNo": null,
		"open": null,
		"list": [{
			"menuId": 212,
			"name": "课程分类",
			"parentId": 211,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "系统管理"
		}, {
			"menuId": 213,
			"name": "帮助中心",
			"parentId": 211,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "系统管理"
		}, {
			"menuId": 214,
			"name": "模板管理",
			"parentId": 211,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "系统管理"
		}],
		"parentName": "系统管理"
	}, {
		"menuId": 215,
		"name": "权限管理",
		"parentId": 1,
		"url": null,
		"perms": null,
		"type": 0,
		"icon": null,
		"orderNo": null,
		"open": null,
		"list": [{
			"menuId": 216,
			"name": "菜单管理",
			"parentId": 215,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "权限管理"
		}, {
			"menuId": 217,
			"name": "角色管理",
			"parentId": 215,
			"url": null,
			"perms": null,
			"type": 1,
			"icon": null,
			"orderNo": null,
			"open": null,
			"list": null,
			"parentName": "权限管理"
		}],
		"parentName": "系统管理"
	}, {
		"menuId": 22,
		"name": "权限管理",
		"parentId": 1,
		"url": null,
		"perms": null,
		"type": 1,
		"icon": "system",
		"orderNo": 1,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 260,
		"name": "教师",
		"parentId": 1,
		"url": "sys/teacher",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 295,
		"name": "学生参与头脑风暴记录",
		"parentId": 1,
		"url": "storm/stormrecord",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 48,
		"name": "用户",
		"parentId": 1,
		"url": "sys/user",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 320,
		"name": "学生",
		"parentId": 1,
		"url": "sys/student",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 68,
		"name": "系统配置",
		"parentId": 1,
		"url": "sys/config",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 73,
		"name": "字典表",
		"parentId": 1,
		"url": "sys/dict",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 78,
		"name": "区域管理",
		"parentId": 1,
		"url": "sys/area",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 83,
		"name": "测试表",
		"parentId": 1,
		"url": "sys/demo",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 90,
		"name": "班级",
		"parentId": 1,
		"url": "sys/class",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 95,
		"name": "标签",
		"parentId": 1,
		"url": "sys/tag",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 365,
		"name": "oss",
		"parentId": 1,
		"url": null,
		"perms": null,
		"type": 1,
		"icon": null,
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 110,
		"name": "管理员",
		"parentId": 1,
		"url": "sys/manager",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 115,
		"name": "租户",
		"parentId": 1,
		"url": "sys/tenant",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 390,
		"name": "证书",
		"parentId": 1,
		"url": "sys/certificate",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 395,
		"name": "证书审核记录",
		"parentId": 1,
		"url": "sys/certificateauditrecord",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 400,
		"name": "证书扩展表",
		"parentId": 1,
		"url": "sys/certificateextension",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 405,
		"name": "用户证书",
		"parentId": 1,
		"url": "sys/certificateuserrecord",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 154,
		"name": "讨论区主题表",
		"parentId": 1,
		"url": "discussion/dicussion",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 410,
		"name": "证书图片表",
		"parentId": 1,
		"url": "sys/certiftcateimg",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 159,
		"name": "讨论区回复表",
		"parentId": 1,
		"url": "discussion/dicussionreply",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 416,
		"name": "租户轮播图",
		"parentId": 1,
		"url": "sys/tenantcarousel",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 421,
		"name": "门户模板",
		"parentId": 1,
		"url": "sys/tenanttemplate",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 426,
		"name": "",
		"parentId": 1,
		"url": "sys/recommend",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 225,
		"name": "系",
		"parentId": 1,
		"url": "sys/department",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 235,
		"name": "院",
		"parentId": 1,
		"url": "sys/college",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 240,
		"name": "院管理员",
		"parentId": 1,
		"url": "sys/collegemanager",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 245,
		"name": "专业",
		"parentId": 1,
		"url": "sys/speciality",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 250,
		"name": "专业管理员",
		"parentId": 1,
		"url": "sys/specialitymanager",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}, {
		"menuId": 255,
		"name": "课程分类",
		"parentId": 1,
		"url": "sys/category",
		"perms": null,
		"type": 1,
		"icon": "config",
		"orderNo": 6,
		"open": null,
		"list": null,
		"parentName": "系统管理"
	}],
	"parentName": null
}, {
	"menuId": 230,
	"name": "系管理员",
	"parentId": 0,
	"url": "sys/departmentmanager",
	"perms": null,
	"type": 1,
	"icon": "config",
	"orderNo": 6,
	"open": null,
	"list": null,
	"parentName": null
}]
      }
    },
    created(){
      // menuList().then((response)=>{
      //   console.log(this.storeNav, '``````', response.data)
        this.$store.commit('setAllMenu',this.menuList)
        // response.data.forEach(element => {
        //   if(element.name === this.storeNav) {
        //     this.menuList = element
        //   }
        // });
      // })
    },
    methods:{
      navChange() {
        this.storeNav = this.$store.state.navHeader
      }
    }
  }
</script>

<style scoped lang="stylus" type="text/stylus">
    .header
        width:100%
        height:60px
        background: #464C5C
        display: flex

        .login
            color: #ffffff
            font-size:30px
            line-height:60px
            padding-left:20px
            margin-right:80px

            .sizes
              font-size:16px
              margin-left:10px
              margin-top:20px
              position: relative
              bottom:-3px

        .list
            display:inline-block
            font-size:18px
            color:#ffffff
            height:60px
            line-height:60px
            padding-left:10px
            padding-right:10px
            margin-right:10px

        .yes-list
            background: #697583
</style>
