let static_routes = [
    {
        "menuId": 1,
        "name": "课程中心",
        "parentId": 0,
        "url": "/course",
        "perms": null,
        "type": 0,
        "icon": null,
        "orderNo": 1,
        "comment": null,
        "menuCode": null,
        "showCode": null,
        "level": 1,
        "redirect": "/course/list",
        "component": "layout/header",
        "open": null,
        "list": [
            {
                "menuId": 90,
                "name": "试题管理",
                "parentId": 1,
                "url": "/test",
                "perms": null,
                "type": 0,
                "icon": null,
                "orderNo": null,
                "comment": null,
                "menuCode": null,
                "showCode": null,
                "level": null,
                "redirect": "/course/resource/test",
                "component": "layout/index",
                "open": null,
                "list": [
                    {
                        "menuId": 91,
                        "name": "试题列表",
                        "parentId": 90,
                        "url": "/course/resource/test",
                        "perms": "course:libraryquiz:list",
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": "",
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "course/resourse/test/test",
                        "open": null,
                        "list": null,
                        "parentName": "试题管理",
                        "isLeaf": null
                    },
                    {
                        "menuId": 95,
                        "name": "保存试题",
                        "parentId": 90,
                        "url": "/course/resource/addtest/:catalog",
                        "perms": "course:libraryquiz:save",
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": 2,
                        "level": null,
                        "redirect": null,
                        "component": "course/resourse/test/addTest",
                        "open": null,
                        "list": null,
                        "parentName": "试题管理",
                        "isLeaf": null
                    },
                    {
                        "menuId": 97,
                        "name": "修改试题",
                        "parentId": 90,
                        "url": "/course/resource/edittest/:quiz",
                        "perms": "course:libraryquiz:update",
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": 2,
                        "level": null,
                        "redirect": null,
                        "component": "course/resourse/test/editTest",
                        "open": null,
                        "list": null,
                        "parentName": "试题管理",
                        "isLeaf": null
                    }
                ],
                "parentName": "课程中心",
                "isLeaf": null
            },
            {
                "menuId": 103,
                "name": "资源管理",
                "parentId": 1,
                "url": "/resource",
                "perms": null,
                "type": 0,
                "icon": null,
                "orderNo": null,
                "comment": null,
                "menuCode": null,
                "showCode": null,
                "level": null,
                "redirect": null,
                "component": "layout/index",
                "open": null,
                "list": [
                    {
                        "menuId": 105,
                        "name": "资源列表",
                        "parentId": 103,
                        "url": "/course/resource/resource",
                        "perms": "course:libraryresource:list",
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "course/resourse/resourse/resourse",
                        "open": null,
                        "list": null,
                        "parentName": "资源管理",
                        "isLeaf": null
                    }
                ],
                "parentName": "课程中心",
                "isLeaf": null
            },
            {
                "menuId": 114,
                "name": "活动管理",
                "parentId": 1,
                "url": "/activity",
                "perms": null,
                "type": 0,
                "icon": null,
                "orderNo": null,
                "comment": null,
                "menuCode": null,
                "showCode": null,
                "level": null,
                "redirect": null,
                "component": "layout/index",
                "open": null,
                "list": [
                    {
                        "menuId": 115,
                        "name": "活动列表",
                        "parentId": 114,
                        "url": "/course/activity/activity",
                        "perms": "course:interaction",
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "course/resourse/activity/activity",
                        "open": null,
                        "list": null,
                        "parentName": "活动管理",
                        "isLeaf": null
                    }
                ],
                "parentName": "课程中心",
                "isLeaf": null
            },
            {
                "menuId": 173,
                "name": "课程列表",
                "parentId": 1,
                "url": "/course/list",
                "perms": null,
                "type": 0,
                "icon": null,
                "orderNo": null,
                "comment": "",
                "menuCode": null,
                "showCode": null,
                "level": 2,
                "redirect": null,
                "component": "layout/index",
                "open": null,
                "list": [
                    {
                        "menuId": 209,
                        "name": "课程容器",
                        "parentId": 173,
                        "url": "/course/list/chapter",
                        "perms": "",
                        "type": 0,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": 2,
                        "level": 2,
                        "redirect": "",
                        "component": "course/courseMain",
                        "open": null,
                        "list": [
                            {
                                "menuId": 46,
                                "name": "互动",
                                "parentId": 209,
                                "url": "/course/list/interact",
                                "perms": "course:interaction",
                                "type": 1,
                                "icon": null,
                                "orderNo": null,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": null,
                                "redirect": null,
                                "component": "course/interact",
                                "open": null,
                                "list": null,
                                "parentName": "课程容器",
                                "isLeaf": null
                            },
                            {
                                "menuId": 50,
                                "name": "教学管理",
                                "parentId": 209,
                                "url": "/course/list/teach",
                                "perms": null,
                                "type": 0,
                                "icon": null,
                                "orderNo": null,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": null,
                                "redirect": "/course/list/teach/grade",
                                "component": "course/teach",
                                "open": null,
                                "list": [
                                    {
                                        "menuId": 33,
                                        "name": "查看测试",
                                        "parentId": 50,
                                        "url": "/course/list/teach/test",
                                        "perms": "course:exam:info,course:exam:list",
                                        "type": 1,
                                        "icon": null,
                                        "orderNo": null,
                                        "comment": null,
                                        "menuCode": null,
                                        "showCode": null,
                                        "level": null,
                                        "redirect": null,
                                        "component": "course/teachContent/test",
                                        "open": null,
                                        "list": null,
                                        "parentName": "教学管理",
                                        "isLeaf": null
                                    },
                                    {
                                        "menuId": 35,
                                        "name": "查看头脑风暴",
                                        "parentId": 50,
                                        "url": "/course/list/teach/storm",
                                        "perms": "course:storm:info",
                                        "type": 1,
                                        "icon": null,
                                        "orderNo": null,
                                        "comment": null,
                                        "menuCode": null,
                                        "showCode": null,
                                        "level": null,
                                        "redirect": null,
                                        "component": "course/teachContent/storm",
                                        "open": null,
                                        "list": null,
                                        "parentName": "教学管理",
                                        "isLeaf": null
                                    },
                                    {
                                        "menuId": 41,
                                        "name": "查看投票",
                                        "parentId": 50,
                                        "url": "/course/list/teach/questionnaire",
                                        "perms": "course:vote:info",
                                        "type": 1,
                                        "icon": null,
                                        "orderNo": null,
                                        "comment": null,
                                        "menuCode": null,
                                        "showCode": null,
                                        "level": null,
                                        "redirect": null,
                                        "component": "course/teachContent/questionnaire",
                                        "open": null,
                                        "list": null,
                                        "parentName": "教学管理",
                                        "isLeaf": null
                                    },
                                    {
                                        "menuId": 43,
                                        "name": "查看作业",
                                        "parentId": 50,
                                        "url": "/course/list/teach/homework",
                                        "perms": "course:homework:info,course:homework:list",
                                        "type": 1,
                                        "icon": null,
                                        "orderNo": null,
                                        "comment": null,
                                        "menuCode": null,
                                        "showCode": null,
                                        "level": null,
                                        "redirect": null,
                                        "component": "course/teachContent/homeworkList",
                                        "open": null,
                                        "list": null,
                                        "parentName": "教学管理",
                                        "isLeaf": null
                                    },
                                    {
                                        "menuId": 61,
                                        "name": "查看成绩",
                                        "parentId": 50,
                                        "url": "/course/list/teach/grade",
                                        "perms": "course:coursescore:info",
                                        "type": 1,
                                        "icon": null,
                                        "orderNo": null,
                                        "comment": null,
                                        "menuCode": null,
                                        "showCode": null,
                                        "level": null,
                                        "redirect": null,
                                        "component": "course/teachContent/grade",
                                        "open": null,
                                        "list": null,
                                        "parentName": "教学管理",
                                        "isLeaf": null
                                    },
                                    {
                                        "menuId": 69,
                                        "name": "作业详情",
                                        "parentId": 50,
                                        "url": "/course/list/teach/homeworkdetail",
                                        "perms": "course:homeworksubmission:info",
                                        "type": 1,
                                        "icon": null,
                                        "orderNo": null,
                                        "comment": null,
                                        "menuCode": null,
                                        "showCode": null,
                                        "level": null,
                                        "redirect": null,
                                        "component": "course/teachContent/homeworkDetail",
                                        "open": null,
                                        "list": null,
                                        "parentName": "教学管理",
                                        "isLeaf": null
                                    },
                                    {
                                        "menuId": 79,
                                        "name": "笔记列表",
                                        "parentId": 50,
                                        "url": "/course/list/teach/notes",
                                        "perms": "course:note:list",
                                        "type": 1,
                                        "icon": null,
                                        "orderNo": null,
                                        "comment": null,
                                        "menuCode": null,
                                        "showCode": null,
                                        "level": null,
                                        "redirect": null,
                                        "component": "course/teachContent/notes",
                                        "open": null,
                                        "list": null,
                                        "parentName": "教学管理",
                                        "isLeaf": null
                                    },
                                    {
                                        "menuId": 210,
                                        "name": "查看视频",
                                        "parentId": 50,
                                        "url": "/course/list/teach/video",
                                        "perms": null,
                                        "type": 1,
                                        "icon": null,
                                        "orderNo": null,
                                        "comment": null,
                                        "menuCode": null,
                                        "showCode": null,
                                        "level": null,
                                        "redirect": null,
                                        "component": "course/teachContent/videos",
                                        "open": null,
                                        "list": null,
                                        "parentName": "教学管理",
                                        "isLeaf": null
                                    },
                                    {
                                        "menuId": 212,
                                        "name": "测试详情",
                                        "parentId": 50,
                                        "url": "/course/list/teach/testmark",
                                        "perms": null,
                                        "type": 1,
                                        "icon": null,
                                        "orderNo": null,
                                        "comment": null,
                                        "menuCode": null,
                                        "showCode": null,
                                        "level": null,
                                        "redirect": null,
                                        "component": "course/teachContent/testMark",
                                        "open": null,
                                        "list": null,
                                        "parentName": "教学管理",
                                        "isLeaf": null
                                    }
                                ],
                                "parentName": "课程容器",
                                "isLeaf": null
                            },
                            {
                                "menuId": 51,
                                "name": "成员列表",
                                "parentId": 209,
                                "url": "/course/list/member",
                                "perms": "course:courseuser:list",
                                "type": 1,
                                "icon": null,
                                "orderNo": null,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": null,
                                "redirect": null,
                                "component": "course/member",
                                "open": null,
                                "list": null,
                                "parentName": "课程容器",
                                "isLeaf": null
                            },
                            {
                                "menuId": 58,
                                "name": "查看小组方案",
                                "parentId": 209,
                                "url": "/course/list/member/manage",
                                "perms": "course:courseteam:list,course:coursescheme:list,course:courseteamuser:list",
                                "type": 1,
                                "icon": null,
                                "orderNo": null,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": null,
                                "redirect": null,
                                "component": "course/memberContent/groupPlan",
                                "open": null,
                                "list": null,
                                "parentName": "课程容器",
                                "isLeaf": null
                            },
                            {
                                "menuId": 83,
                                "name": "通知列表",
                                "parentId": 209,
                                "url": "/course/list/notice",
                                "perms": "course:course:info",
                                "type": 1,
                                "icon": null,
                                "orderNo": null,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": null,
                                "redirect": null,
                                "component": "course/notice",
                                "open": null,
                                "list": null,
                                "parentName": "课程容器",
                                "isLeaf": null
                            },
                            {
                                "menuId": 211,
                                "name": "讨论查看",
                                "parentId": 209,
                                "url": "/course/list/discuss",
                                "perms": null,
                                "type": 1,
                                "icon": null,
                                "orderNo": null,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": null,
                                "redirect": null,
                                "component": "course/discuss",
                                "open": null,
                                "list": null,
                                "parentName": "课程容器",
                                "isLeaf": null
                            },
                            {
                                "menuId": 213,
                                "name": "发布投票",
                                "parentId": 209,
                                "url": "/course/list/interact/vote",
                                "perms": null,
                                "type": 1,
                                "icon": null,
                                "orderNo": null,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": null,
                                "redirect": null,
                                "component": "course/interactContent/vote",
                                "open": null,
                                "list": null,
                                "parentName": "课程容器",
                                "isLeaf": null
                            },
                            {
                                "menuId": 214,
                                "name": "发布头脑风暴",
                                "parentId": 209,
                                "url": "/course/list/interact/brainstorm",
                                "perms": null,
                                "type": 1,
                                "icon": null,
                                "orderNo": null,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": null,
                                "redirect": null,
                                "component": "course/interactContent/brainStorm",
                                "open": null,
                                "list": null,
                                "parentName": "课程容器",
                                "isLeaf": null
                            },
                            {
                                "menuId": 215,
                                "name": "发布作业",
                                "parentId": 209,
                                "url": "/course/list/interact/homework",
                                "perms": null,
                                "type": 1,
                                "icon": null,
                                "orderNo": null,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": null,
                                "redirect": null,
                                "component": "course/interactContent/homeWork",
                                "open": null,
                                "list": null,
                                "parentName": "课程容器",
                                "isLeaf": null
                            },
                            {
                                "menuId": 216,
                                "name": "发布测试",
                                "parentId": 209,
                                "url": "/course/list/interact/test",
                                "perms": null,
                                "type": 1,
                                "icon": null,
                                "orderNo": null,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": null,
                                "redirect": null,
                                "component": "course/interactContent/test",
                                "open": null,
                                "list": null,
                                "parentName": "课程容器",
                                "isLeaf": null
                            },
                            {
                                "menuId": 217,
                                "name": "投票结果",
                                "parentId": 209,
                                "url": "/course/list/interact/voteresult",
                                "perms": null,
                                "type": 1,
                                "icon": null,
                                "orderNo": null,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": null,
                                "redirect": null,
                                "component": "course/interactContent/voteResult",
                                "open": null,
                                "list": null,
                                "parentName": "课程容器",
                                "isLeaf": null
                            },
                            {
                                "menuId": 218,
                                "name": "头脑风暴结果",
                                "parentId": 209,
                                "url": "/course/list/interact/brainresult",
                                "perms": null,
                                "type": 1,
                                "icon": null,
                                "orderNo": null,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": null,
                                "redirect": null,
                                "component": "course/interactContent/brainResult",
                                "open": null,
                                "list": null,
                                "parentName": "课程容器",
                                "isLeaf": null
                            },
                            {
                                "menuId": 219,
                                "name": "作业结果",
                                "parentId": 209,
                                "url": "/course/list/interact/homeworkresult",
                                "perms": null,
                                "type": 1,
                                "icon": null,
                                "orderNo": null,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": null,
                                "redirect": null,
                                "component": "course/interactContent/workResult",
                                "open": null,
                                "list": null,
                                "parentName": "课程容器",
                                "isLeaf": null
                            },
                            {
                                "menuId": 220,
                                "name": "测试结果",
                                "parentId": 209,
                                "url": "/course/list/interact/testresult",
                                "perms": null,
                                "type": 1,
                                "icon": null,
                                "orderNo": null,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": null,
                                "redirect": null,
                                "component": "course/interactContent/testResult",
                                "open": null,
                                "list": null,
                                "parentName": "课程容器",
                                "isLeaf": null
                            },
                            {
                                "menuId": 12,
                                "name": "章节内容",
                                "parentId": 209,
                                "url": "/course/list/chapter",
                                "perms": null,
                                "type": 1,
                                "icon": null,
                                "orderNo": 1,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": 3,
                                "redirect": null,
                                "component": "course/chapter",
                                "open": null,
                                "list": null,
                                "parentName": "课程容器",
                                "isLeaf": null
                            }
                        ],
                        "parentName": "课程列表",
                        "isLeaf": null
                    },
                    {
                        "menuId": 3,
                        "name": "课程列表",
                        "parentId": 173,
                        "url": "/course/list",
                        "perms": "course:course:list",
                        "type": 0,
                        "icon": null,
                        "orderNo": 1,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": "",
                        "component": "course/list",
                        "open": null,
                        "list": [],
                        "parentName": "课程列表",
                        "isLeaf": null
                    },
                    {
                        "menuId": 4,
                        "name": "创建课程",
                        "parentId": 173,
                        "url": "/course/addcourse",
                        "perms": "course:course:save",
                        "type": 0,
                        "icon": null,
                        "orderNo": 1,
                        "comment": null,
                        "menuCode": null,
                        "showCode": 2,
                        "level": null,
                        "redirect": null,
                        "component": "course/addCourse",
                        "open": null,
                        "list": [],
                        "parentName": "课程列表",
                        "isLeaf": null
                    }
                ],
                "parentName": "课程中心",
                "isLeaf": null
            },
            {
                "menuId": 174,
                "name": "课程评价",
                "parentId": 1,
                "url": "/appraisal/list",
                "perms": null,
                "type": 0,
                "icon": null,
                "orderNo": null,
                "comment": null,
                "menuCode": null,
                "showCode": null,
                "level": 2,
                "redirect": "",
                "component": "layout/index",
                "open": null,
                "list": [
                    {
                        "menuId": 86,
                        "name": "课程评价",
                        "parentId": 174,
                        "url": "/appraisal/list",
                        "perms": null,
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": "",
                        "component": "course/appraisal",
                        "open": null,
                        "list": null,
                        "parentName": "课程评价",
                        "isLeaf": null
                    }
                ],
                "parentName": "课程中心",
                "isLeaf": null
            }
        ],
        "parentName": null,
        "isLeaf": null
    },
    {
        "menuId": 169,
        "name": "学习中心",
        "parentId": 0,
        "url": "/learn",
        "perms": "user:list",
        "type": 0,
        "icon": null,
        "orderNo": 2,
        "comment": null,
        "menuCode": null,
        "showCode": null,
        "level": 1,
        "redirect": "/learn/inclass",
        "component": "layout/header",
        "open": null,
        "list": [
            {
                "menuId": 170,
                "name": "学习管理",
                "parentId": 169,
                "url": "/learn/inclass",
                "perms": "user:xxx",
                "type": 0,
                "icon": null,
                "orderNo": null,
                "comment": null,
                "menuCode": null,
                "showCode": null,
                "level": 2,
                "redirect": "",
                "component": "layout/index",
                "open": null,
                "list": [
                    {
                        "menuId": 171,
                        "name": "课堂",
                        "parentId": 170,
                        "url": "/learn/inclass",
                        "perms": "user:xxx",
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": 3,
                        "redirect": "",
                        "component": "learn/inClass",
                        "open": null,
                        "list": null,
                        "parentName": "学习管理",
                        "isLeaf": null
                    },
                    {
                        "menuId": 187,
                        "name": "课后",
                        "parentId": 170,
                        "url": "/learn/afterclass",
                        "perms": null,
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "learn/afterClass",
                        "open": null,
                        "list": null,
                        "parentName": "学习管理",
                        "isLeaf": null
                    }
                ],
                "parentName": "学习中心",
                "isLeaf": null
            }
        ],
        "parentName": null,
        "isLeaf": null
    },
    {
        "menuId": 120,
        "name": "校管中心",
        "parentId": 0,
        "url": "/school",
        "perms": "",
        "type": 0,
        "icon": null,
        "orderNo": 3,
        "comment": null,
        "menuCode": null,
        "showCode": null,
        "level": 1,
        "redirect": "/school/student",
        "component": "layout/header",
        "open": null,
        "list": [
            {
                "menuId": 121,
                "name": "用户管理",
                "parentId": 120,
                "url": "/school/student",
                "perms": null,
                "type": 0,
                "icon": null,
                "orderNo": null,
                "comment": null,
                "menuCode": null,
                "showCode": null,
                "level": null,
                "redirect": null,
                "component": "layout/index",
                "open": null,
                "list": [
                    {
                        "menuId": 123,
                        "name": "学生管理",
                        "parentId": 121,
                        "url": "/school/student",
                        "perms": "sys:student:list",
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "school/student",
                        "open": null,
                        "list": null,
                        "parentName": "用户管理",
                        "isLeaf": null
                    },
                    {
                        "menuId": 133,
                        "name": "教师管理",
                        "parentId": 121,
                        "url": "/school/teacher",
                        "perms": "sys:teacher:info",
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "school/teacher",
                        "open": null,
                        "list": null,
                        "parentName": "用户管理",
                        "isLeaf": null
                    }
                ],
                "parentName": "校管中心",
                "isLeaf": null
            },
            {
                "menuId": 177,
                "name": "门户配置",
                "parentId": 120,
                "url": "/portal",
                "perms": null,
                "type": 0,
                "icon": null,
                "orderNo": null,
                "comment": null,
                "menuCode": null,
                "showCode": null,
                "level": 2,
                "redirect": "/school/portal/mould",
                "component": "layout/index",
                "open": null,
                "list": [
                    {
                        "menuId": 147,
                        "name": "设置门户模板",
                        "parentId": 177,
                        "url": "/school/portal/mould",
                        "perms": "sys:tenant:update",
                        "type": 0,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": 2,
                        "redirect": null,
                        "component": "school/portal",
                        "open": null,
                        "list": [
                            {
                                "menuId": 148,
                                "name": "门户模板列表",
                                "parentId": 147,
                                "url": "/school/portal/mould",
                                "perms": "sys:tenant:info",
                                "type": 1,
                                "icon": null,
                                "orderNo": null,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": 3,
                                "redirect": null,
                                "component": "school/portalMould",
                                "open": null,
                                "list": null,
                                "parentName": "设置门户模板",
                                "isLeaf": null
                            },
                            {
                                "menuId": 150,
                                "name": "获取平台信息",
                                "parentId": 147,
                                "url": "/school/portal/platform",
                                "perms": "sys:tenant:info",
                                "type": 1,
                                "icon": null,
                                "orderNo": null,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": null,
                                "redirect": null,
                                "component": "school/portalPlatform",
                                "open": null,
                                "list": null,
                                "parentName": "设置门户模板",
                                "isLeaf": null
                            },
                            {
                                "menuId": 152,
                                "name": "获取租户轮播图",
                                "parentId": 147,
                                "url": "/school/portal/banner",
                                "perms": "sys:tenantcarousel:info",
                                "type": 1,
                                "icon": null,
                                "orderNo": null,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": null,
                                "redirect": null,
                                "component": "school/portalBanner",
                                "open": null,
                                "list": null,
                                "parentName": "设置门户模板",
                                "isLeaf": null
                            },
                            {
                                "menuId": 155,
                                "name": "名师推荐列表",
                                "parentId": 147,
                                "url": "/school/portal/teacher",
                                "perms": "sys:recommend:list",
                                "type": 1,
                                "icon": null,
                                "orderNo": null,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": null,
                                "redirect": null,
                                "component": "school/portalTeacher",
                                "open": null,
                                "list": null,
                                "parentName": "设置门户模板",
                                "isLeaf": null
                            },
                            {
                                "menuId": 178,
                                "name": "课程推荐列表",
                                "parentId": 147,
                                "url": "/school/portal/recommend",
                                "perms": "sys:recommend:list",
                                "type": 1,
                                "icon": null,
                                "orderNo": null,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": null,
                                "redirect": null,
                                "component": "school/portalRecommend",
                                "open": null,
                                "list": null,
                                "parentName": "设置门户模板",
                                "isLeaf": null
                            }
                        ],
                        "parentName": "门户配置",
                        "isLeaf": null
                    }
                ],
                "parentName": "校管中心",
                "isLeaf": null
            },
            {
                "menuId": 179,
                "name": "消息管理",
                "parentId": 120,
                "url": "/school/notice",
                "perms": null,
                "type": 0,
                "icon": null,
                "orderNo": null,
                "comment": null,
                "menuCode": null,
                "showCode": null,
                "level": null,
                "redirect": null,
                "component": "layout/index",
                "open": null,
                "list": [
                    {
                        "menuId": 180,
                        "name": "消息管理",
                        "parentId": 179,
                        "url": "/school/notice",
                        "perms": null,
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "school/schoolNotice",
                        "open": null,
                        "list": null,
                        "parentName": "消息管理",
                        "isLeaf": null
                    }
                ],
                "parentName": "校管中心",
                "isLeaf": null
            },
            {
                "menuId": 181,
                "name": "课程管理",
                "parentId": 120,
                "url": "/school/course/course",
                "perms": null,
                "type": 0,
                "icon": null,
                "orderNo": null,
                "comment": null,
                "menuCode": null,
                "showCode": null,
                "level": null,
                "redirect": null,
                "component": "layout/index",
                "open": null,
                "list": [
                    {
                        "menuId": 159,
                        "name": "课程管理",
                        "parentId": 181,
                        "url": "/school/course/course",
                        "perms": null,
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "school/course",
                        "open": null,
                        "list": null,
                        "parentName": "课程管理",
                        "isLeaf": null
                    },
                    {
                        "menuId": 162,
                        "name": "证书审核",
                        "parentId": 181,
                        "url": "/school/course/certificate",
                        "perms": "sys:certificate:info",
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "school/certificate",
                        "open": null,
                        "list": null,
                        "parentName": "课程管理",
                        "isLeaf": null
                    }
                ],
                "parentName": "校管中心",
                "isLeaf": null
            },
            {
                "menuId": 182,
                "name": "组织架构",
                "parentId": 120,
                "url": "/school/structure/academy",
                "perms": null,
                "type": 0,
                "icon": null,
                "orderNo": null,
                "comment": null,
                "menuCode": null,
                "showCode": null,
                "level": null,
                "redirect": null,
                "component": "layout/index",
                "open": null,
                "list": [
                    {
                        "menuId": 183,
                        "name": "院管理",
                        "parentId": 182,
                        "url": "/school/structure/academy",
                        "perms": null,
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "school/academy",
                        "open": null,
                        "list": null,
                        "parentName": "组织架构",
                        "isLeaf": null
                    },
                    {
                        "menuId": 184,
                        "name": "系管理",
                        "parentId": 182,
                        "url": "/school/structure/department",
                        "perms": null,
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "school/department",
                        "open": null,
                        "list": null,
                        "parentName": "组织架构",
                        "isLeaf": null
                    },
                    {
                        "menuId": 185,
                        "name": "专业管理",
                        "parentId": 182,
                        "url": "/school/structure/speciality",
                        "perms": null,
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "school/speciality",
                        "open": null,
                        "list": null,
                        "parentName": "组织架构",
                        "isLeaf": null
                    },
                    {
                        "menuId": 186,
                        "name": "班级管理",
                        "parentId": 182,
                        "url": "/school/structure/class",
                        "perms": null,
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "school/class",
                        "open": null,
                        "list": null,
                        "parentName": "组织架构",
                        "isLeaf": null
                    }
                ],
                "parentName": "校管中心",
                "isLeaf": null
            }
        ],
        "parentName": null,
        "isLeaf": null
    },
    {
        "menuId": 164,
        "name": "系统管理",
        "parentId": 0,
        "url": "/system",
        "perms": null,
        "type": 0,
        "icon": null,
        "orderNo": 4,
        "comment": null,
        "menuCode": null,
        "showCode": null,
        "level": 1,
        "redirect": "/system/tenantManager",
        "component": "layout/header",
        "open": null,
        "list": [
            {
                "menuId": 165,
                "name": "租户管理",
                "parentId": 164,
                "url": "/system/tenantManager",
                "perms": "xxx",
                "type": 0,
                "icon": null,
                "orderNo": null,
                "comment": null,
                "menuCode": null,
                "showCode": null,
                "level": 2,
                "redirect": "",
                "component": "layout/index",
                "open": null,
                "list": [
                    {
                        "menuId": 166,
                        "name": "租户管理",
                        "parentId": 165,
                        "url": "/system/tenantManager",
                        "perms": "xxx",
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": 3,
                        "redirect": null,
                        "component": "system/tenantManager",
                        "open": null,
                        "list": null,
                        "parentName": "租户管理",
                        "isLeaf": null
                    },
                    {
                        "menuId": 188,
                        "name": "租户账号管理",
                        "parentId": 165,
                        "url": "/system/tenantAccountManager",
                        "perms": null,
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "system/tenantAccountManager",
                        "open": null,
                        "list": null,
                        "parentName": "租户管理",
                        "isLeaf": null
                    }
                ],
                "parentName": "系统管理",
                "isLeaf": null
            },
            {
                "menuId": 167,
                "name": "权限管理",
                "parentId": 164,
                "url": "/system/power",
                "perms": "xx",
                "type": 0,
                "icon": null,
                "orderNo": null,
                "comment": null,
                "menuCode": null,
                "showCode": null,
                "level": 2,
                "redirect": "",
                "component": "layout/index",
                "open": null,
                "list": [
                    {
                        "menuId": 168,
                        "name": "菜单管理",
                        "parentId": 167,
                        "url": "/system/menu",
                        "perms": "xx",
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": 2,
                        "redirect": "",
                        "component": "system/menu",
                        "open": null,
                        "list": null,
                        "parentName": "权限管理",
                        "isLeaf": null
                    }
                ],
                "parentName": "系统管理",
                "isLeaf": null
            },
            {
                "menuId": 189,
                "name": "系统管理",
                "parentId": 164,
                "url": "/system/courseCategory",
                "perms": null,
                "type": 0,
                "icon": null,
                "orderNo": null,
                "comment": null,
                "menuCode": null,
                "showCode": null,
                "level": null,
                "redirect": null,
                "component": "layout/index",
                "open": null,
                "list": [
                    {
                        "menuId": 190,
                        "name": "课程分类",
                        "parentId": 189,
                        "url": "/system/courseCategory",
                        "perms": null,
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "system/courseCategory",
                        "open": null,
                        "list": null,
                        "parentName": "系统管理",
                        "isLeaf": null
                    },
                    {
                        "menuId": 191,
                        "name": "帮助中心管理",
                        "parentId": 189,
                        "url": "/system/help",
                        "perms": null,
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "system/help",
                        "open": null,
                        "list": null,
                        "parentName": "系统管理",
                        "isLeaf": null
                    },
                    {
                        "menuId": 192,
                        "name": "消息管理",
                        "parentId": 189,
                        "url": "/system/notice",
                        "perms": null,
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "system/sysNotice",
                        "open": null,
                        "list": null,
                        "parentName": "系统管理",
                        "isLeaf": null
                    }
                ],
                "parentName": "系统管理",
                "isLeaf": null
            },
            {
                "menuId": 193,
                "name": "用户中心",
                "parentId": 164,
                "url": "/system/student",
                "perms": null,
                "type": 0,
                "icon": null,
                "orderNo": null,
                "comment": null,
                "menuCode": null,
                "showCode": null,
                "level": null,
                "redirect": null,
                "component": "layout/index",
                "open": null,
                "list": [
                    {
                        "menuId": 194,
                        "name": "学生管理",
                        "parentId": 193,
                        "url": "/system/student",
                        "perms": null,
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "system/student",
                        "open": null,
                        "list": null,
                        "parentName": "用户中心",
                        "isLeaf": null
                    },
                    {
                        "menuId": 195,
                        "name": "教师管理",
                        "parentId": 193,
                        "url": "/system/teacher",
                        "perms": null,
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "system/teacher",
                        "open": null,
                        "list": null,
                        "parentName": "用户中心",
                        "isLeaf": null
                    },
                    {
                        "menuId": 196,
                        "name": "学校管理员",
                        "parentId": 193,
                        "url": "/system/school",
                        "perms": null,
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "system/school",
                        "open": null,
                        "list": null,
                        "parentName": "用户中心",
                        "isLeaf": null
                    },
                    {
                        "menuId": 197,
                        "name": "系统管理员",
                        "parentId": 193,
                        "url": "/system/manager",
                        "perms": null,
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "system/system",
                        "open": null,
                        "list": null,
                        "parentName": "用户中心",
                        "isLeaf": null
                    },
                    {
                        "menuId": 198,
                        "name": "标签管理",
                        "parentId": 193,
                        "url": "/system/tag",
                        "perms": null,
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "system/tag",
                        "open": null,
                        "list": null,
                        "parentName": "用户中心",
                        "isLeaf": null
                    }
                ],
                "parentName": "系统管理",
                "isLeaf": null
            },
            {
                "menuId": 199,
                "name": "权限管理",
                "parentId": 164,
                "url": "/system/menu",
                "perms": null,
                "type": 0,
                "icon": null,
                "orderNo": null,
                "comment": null,
                "menuCode": null,
                "showCode": null,
                "level": null,
                "redirect": null,
                "component": "layout/index",
                "open": null,
                "list": [
                    {
                        "menuId": 200,
                        "name": "菜单管理",
                        "parentId": 199,
                        "url": "/system/menu",
                        "perms": null,
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "system/menu",
                        "open": null,
                        "list": null,
                        "parentName": "权限管理",
                        "isLeaf": null
                    },
                    {
                        "menuId": 201,
                        "name": "角色管理",
                        "parentId": 199,
                        "url": "/system/role",
                        "perms": null,
                        "type": 1,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "system/role",
                        "open": null,
                        "list": null,
                        "parentName": "权限管理",
                        "isLeaf": null
                    }
                ],
                "parentName": "系统管理",
                "isLeaf": null
            },
            {
                "menuId": 202,
                "name": "门户配置",
                "parentId": 164,
                "url": "/system/school",
                "perms": null,
                "type": 0,
                "icon": null,
                "orderNo": null,
                "comment": null,
                "menuCode": null,
                "showCode": null,
                "level": null,
                "redirect": null,
                "component": "layout/index",
                "open": null,
                "list": [
                    {
                        "menuId": 203,
                        "name": "模板配置",
                        "parentId": 202,
                        "url": "/system/portal/mould",
                        "perms": null,
                        "type": 0,
                        "icon": null,
                        "orderNo": null,
                        "comment": null,
                        "menuCode": null,
                        "showCode": null,
                        "level": null,
                        "redirect": null,
                        "component": "system/portal",
                        "open": null,
                        "list": [
                            {
                                "menuId": 204,
                                "name": "模板配置",
                                "parentId": 203,
                                "url": "/system/portal/mould",
                                "perms": null,
                                "type": 1,
                                "icon": null,
                                "orderNo": null,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": null,
                                "redirect": null,
                                "component": "system/portalMould",
                                "open": null,
                                "list": null,
                                "parentName": "模板配置",
                                "isLeaf": null
                            },
                            {
                                "menuId": 205,
                                "name": "平台信息",
                                "parentId": 203,
                                "url": "/system/portal/platform",
                                "perms": null,
                                "type": 1,
                                "icon": null,
                                "orderNo": null,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": null,
                                "redirect": null,
                                "component": "system/portalPlatform",
                                "open": null,
                                "list": null,
                                "parentName": "模板配置",
                                "isLeaf": null
                            },
                            {
                                "menuId": 206,
                                "name": "轮播图",
                                "parentId": 203,
                                "url": "/system/portal/banner",
                                "perms": null,
                                "type": 1,
                                "icon": null,
                                "orderNo": null,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": null,
                                "redirect": null,
                                "component": "system/portalBanner",
                                "open": null,
                                "list": null,
                                "parentName": "模板配置",
                                "isLeaf": null
                            },
                            {
                                "menuId": 207,
                                "name": "课程推荐",
                                "parentId": 203,
                                "url": "/system/portal/recommend",
                                "perms": null,
                                "type": 1,
                                "icon": null,
                                "orderNo": null,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": null,
                                "redirect": null,
                                "component": "system/portalRecommend",
                                "open": null,
                                "list": null,
                                "parentName": "模板配置",
                                "isLeaf": null
                            },
                            {
                                "menuId": 208,
                                "name": "名师风采",
                                "parentId": 203,
                                "url": "/system/portal/teacher",
                                "perms": null,
                                "type": 1,
                                "icon": null,
                                "orderNo": null,
                                "comment": null,
                                "menuCode": null,
                                "showCode": null,
                                "level": null,
                                "redirect": null,
                                "component": "system/portalTeacher",
                                "open": null,
                                "list": null,
                                "parentName": "模板配置",
                                "isLeaf": null
                            }
                        ],
                        "parentName": "门户配置",
                        "isLeaf": null
                    }
                ],
                "parentName": "系统管理",
                "isLeaf": null
            }
        ],
        "parentName": null,
        "isLeaf": null
    }
]

export {static_routes}